language: swift
osx_image: xcode9.1
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- brew install carthage
- cd Demo
- carthage update --platform iOS
- brew cask install fastlane

script:
- cd ..
- fastlane verify
